# Generated by Django 3.1 on 2023-09-10 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2023, 12, 31)),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='updated_at',
            field=models.DateTimeField(default=datetime.date(2023, 12, 31)),
        ),
    ]
